// SPDX-License-Identifier: MIT
// Copyright (C) 2026 go-ha-catalog authors.

// Code generated by script/gen from Home Assistant 2026.9.1. DO NOT EDIT.

package hacatalog

// Platform is an MQTT-capable Home Assistant platform. It is the value of a
// device bundle's components[*].platform, and the whitelist Home Assistant
// validates that key against.
type Platform string

const (
	PlatformAlarmControlPanel Platform = "alarm_control_panel"
	PlatformBinarySensor      Platform = "binary_sensor"
	PlatformButton            Platform = "button"
	PlatformCamera            Platform = "camera"
	PlatformClimate           Platform = "climate"
	PlatformCover             Platform = "cover"
	PlatformDate              Platform = "date"
	PlatformDatetime          Platform = "datetime"
	PlatformDeviceAutomation  Platform = "device_automation"
	PlatformDeviceTracker     Platform = "device_tracker"
	PlatformEvent             Platform = "event"
	PlatformFan               Platform = "fan"
	PlatformHumidifier        Platform = "humidifier"
	PlatformImage             Platform = "image"
	PlatformInfrared          Platform = "infrared"
	PlatformLawnMower         Platform = "lawn_mower"
	PlatformLight             Platform = "light"
	PlatformLock              Platform = "lock"
	PlatformNotify            Platform = "notify"
	PlatformNumber            Platform = "number"
	PlatformScene             Platform = "scene"
	PlatformSelect            Platform = "select"
	PlatformSensor            Platform = "sensor"
	PlatformSiren             Platform = "siren"
	PlatformSwitch            Platform = "switch"
	PlatformTag               Platform = "tag"
	PlatformText              Platform = "text"
	PlatformTime              Platform = "time"
	PlatformUpdate            Platform = "update"
	PlatformVacuum            Platform = "vacuum"
	PlatformValve             Platform = "valve"
	PlatformWaterHeater       Platform = "water_heater"
)

// String returns the wire value.
func (v Platform) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v Platform) Valid() bool {
	_, ok := validPlatform[v]
	return ok
}

var validPlatform = map[Platform]struct{}{
	PlatformAlarmControlPanel: {},
	PlatformBinarySensor:      {},
	PlatformButton:            {},
	PlatformCamera:            {},
	PlatformClimate:           {},
	PlatformCover:             {},
	PlatformDate:              {},
	PlatformDatetime:          {},
	PlatformDeviceAutomation:  {},
	PlatformDeviceTracker:     {},
	PlatformEvent:             {},
	PlatformFan:               {},
	PlatformHumidifier:        {},
	PlatformImage:             {},
	PlatformInfrared:          {},
	PlatformLawnMower:         {},
	PlatformLight:             {},
	PlatformLock:              {},
	PlatformNotify:            {},
	PlatformNumber:            {},
	PlatformScene:             {},
	PlatformSelect:            {},
	PlatformSensor:            {},
	PlatformSiren:             {},
	PlatformSwitch:            {},
	PlatformTag:               {},
	PlatformText:              {},
	PlatformTime:              {},
	PlatformUpdate:            {},
	PlatformVacuum:            {},
	PlatformValve:             {},
	PlatformWaterHeater:       {},
}

// Platforms lists every MQTT-capable platform, in Home Assistant's own order.
var Platforms = []Platform{
	PlatformAlarmControlPanel,
	PlatformBinarySensor,
	PlatformButton,
	PlatformCamera,
	PlatformClimate,
	PlatformCover,
	PlatformDate,
	PlatformDatetime,
	PlatformDeviceAutomation,
	PlatformDeviceTracker,
	PlatformEvent,
	PlatformFan,
	PlatformHumidifier,
	PlatformImage,
	PlatformInfrared,
	PlatformLawnMower,
	PlatformLight,
	PlatformLock,
	PlatformNotify,
	PlatformNumber,
	PlatformScene,
	PlatformSiren,
	PlatformSelect,
	PlatformSensor,
	PlatformSwitch,
	PlatformTag,
	PlatformText,
	PlatformTime,
	PlatformUpdate,
	PlatformVacuum,
	PlatformValve,
	PlatformWaterHeater,
}

// EntityCategory is Home Assistant's entity category: a hint that an entity is
// configuration or diagnostics rather than primary state.
type EntityCategory string

const (
	EntityCategoryConfig     EntityCategory = "config"
	EntityCategoryDiagnostic EntityCategory = "diagnostic"
)

// String returns the wire value.
func (v EntityCategory) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v EntityCategory) Valid() bool {
	_, ok := validEntityCategory[v]
	return ok
}

var validEntityCategory = map[EntityCategory]struct{}{
	EntityCategoryConfig:     {},
	EntityCategoryDiagnostic: {},
}

// StateClass tells Home Assistant how to aggregate a sensor over time. Getting
// it wrong corrupts long-term statistics irreversibly, so check it against
// [Relations.SensorDeviceClassStateClasses] rather than guessing.
type StateClass string

const (
	StateClassMeasurement      StateClass = "measurement"
	StateClassMeasurementAngle StateClass = "measurement_angle"
	StateClassTotal            StateClass = "total"
	StateClassTotalIncreasing  StateClass = "total_increasing"
)

// String returns the wire value.
func (v StateClass) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v StateClass) Valid() bool {
	_, ok := validStateClass[v]
	return ok
}

var validStateClass = map[StateClass]struct{}{
	StateClassMeasurement:      {},
	StateClassMeasurementAngle: {},
	StateClassTotal:            {},
	StateClassTotalIncreasing:  {},
}

// SensorDeviceClass is the device class vocabulary of the sensor platform.
type SensorDeviceClass string

const (
	SensorDeviceClassAbsoluteHumidity              SensorDeviceClass = "absolute_humidity"
	SensorDeviceClassApparentPower                 SensorDeviceClass = "apparent_power"
	SensorDeviceClassAQI                           SensorDeviceClass = "aqi"
	SensorDeviceClassArea                          SensorDeviceClass = "area"
	SensorDeviceClassAtmosphericPressure           SensorDeviceClass = "atmospheric_pressure"
	SensorDeviceClassBattery                       SensorDeviceClass = "battery"
	SensorDeviceClassBloodGlucoseConcentration     SensorDeviceClass = "blood_glucose_concentration"
	SensorDeviceClassCarbonDioxide                 SensorDeviceClass = "carbon_dioxide"
	SensorDeviceClassCarbonMonoxide                SensorDeviceClass = "carbon_monoxide"
	SensorDeviceClassConductivity                  SensorDeviceClass = "conductivity"
	SensorDeviceClassCurrent                       SensorDeviceClass = "current"
	SensorDeviceClassDataRate                      SensorDeviceClass = "data_rate"
	SensorDeviceClassDataSize                      SensorDeviceClass = "data_size"
	SensorDeviceClassDate                          SensorDeviceClass = "date"
	SensorDeviceClassDistance                      SensorDeviceClass = "distance"
	SensorDeviceClassDuration                      SensorDeviceClass = "duration"
	SensorDeviceClassEnergy                        SensorDeviceClass = "energy"
	SensorDeviceClassEnergyDistance                SensorDeviceClass = "energy_distance"
	SensorDeviceClassEnergyStorage                 SensorDeviceClass = "energy_storage"
	SensorDeviceClassEnum                          SensorDeviceClass = "enum"
	SensorDeviceClassFrequency                     SensorDeviceClass = "frequency"
	SensorDeviceClassGas                           SensorDeviceClass = "gas"
	SensorDeviceClassHumidity                      SensorDeviceClass = "humidity"
	SensorDeviceClassIlluminance                   SensorDeviceClass = "illuminance"
	SensorDeviceClassIrradiance                    SensorDeviceClass = "irradiance"
	SensorDeviceClassMoisture                      SensorDeviceClass = "moisture"
	SensorDeviceClassMonetary                      SensorDeviceClass = "monetary"
	SensorDeviceClassNitrogenDioxide               SensorDeviceClass = "nitrogen_dioxide"
	SensorDeviceClassNitrogenMonoxide              SensorDeviceClass = "nitrogen_monoxide"
	SensorDeviceClassNitrousOxide                  SensorDeviceClass = "nitrous_oxide"
	SensorDeviceClassOzone                         SensorDeviceClass = "ozone"
	SensorDeviceClassPH                            SensorDeviceClass = "ph"
	SensorDeviceClassPM1                           SensorDeviceClass = "pm1"
	SensorDeviceClassPM10                          SensorDeviceClass = "pm10"
	SensorDeviceClassPM25                          SensorDeviceClass = "pm25"
	SensorDeviceClassPm4                           SensorDeviceClass = "pm4"
	SensorDeviceClassPower                         SensorDeviceClass = "power"
	SensorDeviceClassPowerFactor                   SensorDeviceClass = "power_factor"
	SensorDeviceClassPrecipitation                 SensorDeviceClass = "precipitation"
	SensorDeviceClassPrecipitationIntensity        SensorDeviceClass = "precipitation_intensity"
	SensorDeviceClassPressure                      SensorDeviceClass = "pressure"
	SensorDeviceClassRadon                         SensorDeviceClass = "radon"
	SensorDeviceClassReactiveEnergy                SensorDeviceClass = "reactive_energy"
	SensorDeviceClassReactivePower                 SensorDeviceClass = "reactive_power"
	SensorDeviceClassSignalStrength                SensorDeviceClass = "signal_strength"
	SensorDeviceClassSoundPressure                 SensorDeviceClass = "sound_pressure"
	SensorDeviceClassSpeed                         SensorDeviceClass = "speed"
	SensorDeviceClassSulphurDioxide                SensorDeviceClass = "sulphur_dioxide"
	SensorDeviceClassTemperature                   SensorDeviceClass = "temperature"
	SensorDeviceClassTemperatureDelta              SensorDeviceClass = "temperature_delta"
	SensorDeviceClassTimestamp                     SensorDeviceClass = "timestamp"
	SensorDeviceClassUptime                        SensorDeviceClass = "uptime"
	SensorDeviceClassVolatileOrganicCompounds      SensorDeviceClass = "volatile_organic_compounds"
	SensorDeviceClassVolatileOrganicCompoundsParts SensorDeviceClass = "volatile_organic_compounds_parts"
	SensorDeviceClassVoltage                       SensorDeviceClass = "voltage"
	SensorDeviceClassVolume                        SensorDeviceClass = "volume"
	SensorDeviceClassVolumeFlowRate                SensorDeviceClass = "volume_flow_rate"
	SensorDeviceClassVolumeStorage                 SensorDeviceClass = "volume_storage"
	SensorDeviceClassWater                         SensorDeviceClass = "water"
	SensorDeviceClassWeight                        SensorDeviceClass = "weight"
	SensorDeviceClassWindDirection                 SensorDeviceClass = "wind_direction"
	SensorDeviceClassWindSpeed                     SensorDeviceClass = "wind_speed"
)

// String returns the wire value.
func (v SensorDeviceClass) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v SensorDeviceClass) Valid() bool {
	_, ok := validSensorDeviceClass[v]
	return ok
}

var validSensorDeviceClass = map[SensorDeviceClass]struct{}{
	SensorDeviceClassAbsoluteHumidity:              {},
	SensorDeviceClassApparentPower:                 {},
	SensorDeviceClassAQI:                           {},
	SensorDeviceClassArea:                          {},
	SensorDeviceClassAtmosphericPressure:           {},
	SensorDeviceClassBattery:                       {},
	SensorDeviceClassBloodGlucoseConcentration:     {},
	SensorDeviceClassCarbonDioxide:                 {},
	SensorDeviceClassCarbonMonoxide:                {},
	SensorDeviceClassConductivity:                  {},
	SensorDeviceClassCurrent:                       {},
	SensorDeviceClassDataRate:                      {},
	SensorDeviceClassDataSize:                      {},
	SensorDeviceClassDate:                          {},
	SensorDeviceClassDistance:                      {},
	SensorDeviceClassDuration:                      {},
	SensorDeviceClassEnergy:                        {},
	SensorDeviceClassEnergyDistance:                {},
	SensorDeviceClassEnergyStorage:                 {},
	SensorDeviceClassEnum:                          {},
	SensorDeviceClassFrequency:                     {},
	SensorDeviceClassGas:                           {},
	SensorDeviceClassHumidity:                      {},
	SensorDeviceClassIlluminance:                   {},
	SensorDeviceClassIrradiance:                    {},
	SensorDeviceClassMoisture:                      {},
	SensorDeviceClassMonetary:                      {},
	SensorDeviceClassNitrogenDioxide:               {},
	SensorDeviceClassNitrogenMonoxide:              {},
	SensorDeviceClassNitrousOxide:                  {},
	SensorDeviceClassOzone:                         {},
	SensorDeviceClassPH:                            {},
	SensorDeviceClassPM1:                           {},
	SensorDeviceClassPM10:                          {},
	SensorDeviceClassPM25:                          {},
	SensorDeviceClassPm4:                           {},
	SensorDeviceClassPower:                         {},
	SensorDeviceClassPowerFactor:                   {},
	SensorDeviceClassPrecipitation:                 {},
	SensorDeviceClassPrecipitationIntensity:        {},
	SensorDeviceClassPressure:                      {},
	SensorDeviceClassRadon:                         {},
	SensorDeviceClassReactiveEnergy:                {},
	SensorDeviceClassReactivePower:                 {},
	SensorDeviceClassSignalStrength:                {},
	SensorDeviceClassSoundPressure:                 {},
	SensorDeviceClassSpeed:                         {},
	SensorDeviceClassSulphurDioxide:                {},
	SensorDeviceClassTemperature:                   {},
	SensorDeviceClassTemperatureDelta:              {},
	SensorDeviceClassTimestamp:                     {},
	SensorDeviceClassUptime:                        {},
	SensorDeviceClassVolatileOrganicCompounds:      {},
	SensorDeviceClassVolatileOrganicCompoundsParts: {},
	SensorDeviceClassVoltage:                       {},
	SensorDeviceClassVolume:                        {},
	SensorDeviceClassVolumeFlowRate:                {},
	SensorDeviceClassVolumeStorage:                 {},
	SensorDeviceClassWater:                         {},
	SensorDeviceClassWeight:                        {},
	SensorDeviceClassWindDirection:                 {},
	SensorDeviceClassWindSpeed:                     {},
}

// BinarySensorDeviceClass is the device class vocabulary of the binary_sensor platform.
type BinarySensorDeviceClass string

const (
	BinarySensorDeviceClassBattery         BinarySensorDeviceClass = "battery"
	BinarySensorDeviceClassBatteryCharging BinarySensorDeviceClass = "battery_charging"
	BinarySensorDeviceClassCarbonMonoxide  BinarySensorDeviceClass = "carbon_monoxide"
	BinarySensorDeviceClassCold            BinarySensorDeviceClass = "cold"
	BinarySensorDeviceClassConnectivity    BinarySensorDeviceClass = "connectivity"
	BinarySensorDeviceClassDoor            BinarySensorDeviceClass = "door"
	BinarySensorDeviceClassGarageDoor      BinarySensorDeviceClass = "garage_door"
	BinarySensorDeviceClassGas             BinarySensorDeviceClass = "gas"
	BinarySensorDeviceClassHeat            BinarySensorDeviceClass = "heat"
	BinarySensorDeviceClassLight           BinarySensorDeviceClass = "light"
	BinarySensorDeviceClassLock            BinarySensorDeviceClass = "lock"
	BinarySensorDeviceClassMoisture        BinarySensorDeviceClass = "moisture"
	BinarySensorDeviceClassMotion          BinarySensorDeviceClass = "motion"
	BinarySensorDeviceClassMoving          BinarySensorDeviceClass = "moving"
	BinarySensorDeviceClassOccupancy       BinarySensorDeviceClass = "occupancy"
	BinarySensorDeviceClassOpening         BinarySensorDeviceClass = "opening"
	BinarySensorDeviceClassPlug            BinarySensorDeviceClass = "plug"
	BinarySensorDeviceClassPower           BinarySensorDeviceClass = "power"
	BinarySensorDeviceClassPresence        BinarySensorDeviceClass = "presence"
	BinarySensorDeviceClassProblem         BinarySensorDeviceClass = "problem"
	BinarySensorDeviceClassRunning         BinarySensorDeviceClass = "running"
	BinarySensorDeviceClassSafety          BinarySensorDeviceClass = "safety"
	BinarySensorDeviceClassSmoke           BinarySensorDeviceClass = "smoke"
	BinarySensorDeviceClassSound           BinarySensorDeviceClass = "sound"
	BinarySensorDeviceClassTamper          BinarySensorDeviceClass = "tamper"
	BinarySensorDeviceClassUpdate          BinarySensorDeviceClass = "update"
	BinarySensorDeviceClassVibration       BinarySensorDeviceClass = "vibration"
	BinarySensorDeviceClassWindow          BinarySensorDeviceClass = "window"
)

// String returns the wire value.
func (v BinarySensorDeviceClass) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v BinarySensorDeviceClass) Valid() bool {
	_, ok := validBinarySensorDeviceClass[v]
	return ok
}

var validBinarySensorDeviceClass = map[BinarySensorDeviceClass]struct{}{
	BinarySensorDeviceClassBattery:         {},
	BinarySensorDeviceClassBatteryCharging: {},
	BinarySensorDeviceClassCarbonMonoxide:  {},
	BinarySensorDeviceClassCold:            {},
	BinarySensorDeviceClassConnectivity:    {},
	BinarySensorDeviceClassDoor:            {},
	BinarySensorDeviceClassGarageDoor:      {},
	BinarySensorDeviceClassGas:             {},
	BinarySensorDeviceClassHeat:            {},
	BinarySensorDeviceClassLight:           {},
	BinarySensorDeviceClassLock:            {},
	BinarySensorDeviceClassMoisture:        {},
	BinarySensorDeviceClassMotion:          {},
	BinarySensorDeviceClassMoving:          {},
	BinarySensorDeviceClassOccupancy:       {},
	BinarySensorDeviceClassOpening:         {},
	BinarySensorDeviceClassPlug:            {},
	BinarySensorDeviceClassPower:           {},
	BinarySensorDeviceClassPresence:        {},
	BinarySensorDeviceClassProblem:         {},
	BinarySensorDeviceClassRunning:         {},
	BinarySensorDeviceClassSafety:          {},
	BinarySensorDeviceClassSmoke:           {},
	BinarySensorDeviceClassSound:           {},
	BinarySensorDeviceClassTamper:          {},
	BinarySensorDeviceClassUpdate:          {},
	BinarySensorDeviceClassVibration:       {},
	BinarySensorDeviceClassWindow:          {},
}

// NumberDeviceClass is the device class vocabulary of the number platform.
type NumberDeviceClass string

const (
	NumberDeviceClassAbsoluteHumidity              NumberDeviceClass = "absolute_humidity"
	NumberDeviceClassApparentPower                 NumberDeviceClass = "apparent_power"
	NumberDeviceClassAQI                           NumberDeviceClass = "aqi"
	NumberDeviceClassArea                          NumberDeviceClass = "area"
	NumberDeviceClassAtmosphericPressure           NumberDeviceClass = "atmospheric_pressure"
	NumberDeviceClassBattery                       NumberDeviceClass = "battery"
	NumberDeviceClassBloodGlucoseConcentration     NumberDeviceClass = "blood_glucose_concentration"
	NumberDeviceClassCarbonDioxide                 NumberDeviceClass = "carbon_dioxide"
	NumberDeviceClassCarbonMonoxide                NumberDeviceClass = "carbon_monoxide"
	NumberDeviceClassConductivity                  NumberDeviceClass = "conductivity"
	NumberDeviceClassCurrent                       NumberDeviceClass = "current"
	NumberDeviceClassDataRate                      NumberDeviceClass = "data_rate"
	NumberDeviceClassDataSize                      NumberDeviceClass = "data_size"
	NumberDeviceClassDistance                      NumberDeviceClass = "distance"
	NumberDeviceClassDuration                      NumberDeviceClass = "duration"
	NumberDeviceClassEnergy                        NumberDeviceClass = "energy"
	NumberDeviceClassEnergyDistance                NumberDeviceClass = "energy_distance"
	NumberDeviceClassEnergyStorage                 NumberDeviceClass = "energy_storage"
	NumberDeviceClassFrequency                     NumberDeviceClass = "frequency"
	NumberDeviceClassGas                           NumberDeviceClass = "gas"
	NumberDeviceClassHumidity                      NumberDeviceClass = "humidity"
	NumberDeviceClassIlluminance                   NumberDeviceClass = "illuminance"
	NumberDeviceClassIrradiance                    NumberDeviceClass = "irradiance"
	NumberDeviceClassMoisture                      NumberDeviceClass = "moisture"
	NumberDeviceClassMonetary                      NumberDeviceClass = "monetary"
	NumberDeviceClassNitrogenDioxide               NumberDeviceClass = "nitrogen_dioxide"
	NumberDeviceClassNitrogenMonoxide              NumberDeviceClass = "nitrogen_monoxide"
	NumberDeviceClassNitrousOxide                  NumberDeviceClass = "nitrous_oxide"
	NumberDeviceClassOzone                         NumberDeviceClass = "ozone"
	NumberDeviceClassPH                            NumberDeviceClass = "ph"
	NumberDeviceClassPM1                           NumberDeviceClass = "pm1"
	NumberDeviceClassPM10                          NumberDeviceClass = "pm10"
	NumberDeviceClassPM25                          NumberDeviceClass = "pm25"
	NumberDeviceClassPm4                           NumberDeviceClass = "pm4"
	NumberDeviceClassPower                         NumberDeviceClass = "power"
	NumberDeviceClassPowerFactor                   NumberDeviceClass = "power_factor"
	NumberDeviceClassPrecipitation                 NumberDeviceClass = "precipitation"
	NumberDeviceClassPrecipitationIntensity        NumberDeviceClass = "precipitation_intensity"
	NumberDeviceClassPressure                      NumberDeviceClass = "pressure"
	NumberDeviceClassRadon                         NumberDeviceClass = "radon"
	NumberDeviceClassReactiveEnergy                NumberDeviceClass = "reactive_energy"
	NumberDeviceClassReactivePower                 NumberDeviceClass = "reactive_power"
	NumberDeviceClassSignalStrength                NumberDeviceClass = "signal_strength"
	NumberDeviceClassSoundPressure                 NumberDeviceClass = "sound_pressure"
	NumberDeviceClassSpeed                         NumberDeviceClass = "speed"
	NumberDeviceClassSulphurDioxide                NumberDeviceClass = "sulphur_dioxide"
	NumberDeviceClassTemperature                   NumberDeviceClass = "temperature"
	NumberDeviceClassTemperatureDelta              NumberDeviceClass = "temperature_delta"
	NumberDeviceClassVolatileOrganicCompounds      NumberDeviceClass = "volatile_organic_compounds"
	NumberDeviceClassVolatileOrganicCompoundsParts NumberDeviceClass = "volatile_organic_compounds_parts"
	NumberDeviceClassVoltage                       NumberDeviceClass = "voltage"
	NumberDeviceClassVolume                        NumberDeviceClass = "volume"
	NumberDeviceClassVolumeFlowRate                NumberDeviceClass = "volume_flow_rate"
	NumberDeviceClassVolumeStorage                 NumberDeviceClass = "volume_storage"
	NumberDeviceClassWater                         NumberDeviceClass = "water"
	NumberDeviceClassWeight                        NumberDeviceClass = "weight"
	NumberDeviceClassWindDirection                 NumberDeviceClass = "wind_direction"
	NumberDeviceClassWindSpeed                     NumberDeviceClass = "wind_speed"
)

// String returns the wire value.
func (v NumberDeviceClass) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v NumberDeviceClass) Valid() bool {
	_, ok := validNumberDeviceClass[v]
	return ok
}

var validNumberDeviceClass = map[NumberDeviceClass]struct{}{
	NumberDeviceClassAbsoluteHumidity:              {},
	NumberDeviceClassApparentPower:                 {},
	NumberDeviceClassAQI:                           {},
	NumberDeviceClassArea:                          {},
	NumberDeviceClassAtmosphericPressure:           {},
	NumberDeviceClassBattery:                       {},
	NumberDeviceClassBloodGlucoseConcentration:     {},
	NumberDeviceClassCarbonDioxide:                 {},
	NumberDeviceClassCarbonMonoxide:                {},
	NumberDeviceClassConductivity:                  {},
	NumberDeviceClassCurrent:                       {},
	NumberDeviceClassDataRate:                      {},
	NumberDeviceClassDataSize:                      {},
	NumberDeviceClassDistance:                      {},
	NumberDeviceClassDuration:                      {},
	NumberDeviceClassEnergy:                        {},
	NumberDeviceClassEnergyDistance:                {},
	NumberDeviceClassEnergyStorage:                 {},
	NumberDeviceClassFrequency:                     {},
	NumberDeviceClassGas:                           {},
	NumberDeviceClassHumidity:                      {},
	NumberDeviceClassIlluminance:                   {},
	NumberDeviceClassIrradiance:                    {},
	NumberDeviceClassMoisture:                      {},
	NumberDeviceClassMonetary:                      {},
	NumberDeviceClassNitrogenDioxide:               {},
	NumberDeviceClassNitrogenMonoxide:              {},
	NumberDeviceClassNitrousOxide:                  {},
	NumberDeviceClassOzone:                         {},
	NumberDeviceClassPH:                            {},
	NumberDeviceClassPM1:                           {},
	NumberDeviceClassPM10:                          {},
	NumberDeviceClassPM25:                          {},
	NumberDeviceClassPm4:                           {},
	NumberDeviceClassPower:                         {},
	NumberDeviceClassPowerFactor:                   {},
	NumberDeviceClassPrecipitation:                 {},
	NumberDeviceClassPrecipitationIntensity:        {},
	NumberDeviceClassPressure:                      {},
	NumberDeviceClassRadon:                         {},
	NumberDeviceClassReactiveEnergy:                {},
	NumberDeviceClassReactivePower:                 {},
	NumberDeviceClassSignalStrength:                {},
	NumberDeviceClassSoundPressure:                 {},
	NumberDeviceClassSpeed:                         {},
	NumberDeviceClassSulphurDioxide:                {},
	NumberDeviceClassTemperature:                   {},
	NumberDeviceClassTemperatureDelta:              {},
	NumberDeviceClassVolatileOrganicCompounds:      {},
	NumberDeviceClassVolatileOrganicCompoundsParts: {},
	NumberDeviceClassVoltage:                       {},
	NumberDeviceClassVolume:                        {},
	NumberDeviceClassVolumeFlowRate:                {},
	NumberDeviceClassVolumeStorage:                 {},
	NumberDeviceClassWater:                         {},
	NumberDeviceClassWeight:                        {},
	NumberDeviceClassWindDirection:                 {},
	NumberDeviceClassWindSpeed:                     {},
}

// CoverDeviceClass is the device class vocabulary of the cover platform.
type CoverDeviceClass string

const (
	CoverDeviceClassAwning  CoverDeviceClass = "awning"
	CoverDeviceClassBlind   CoverDeviceClass = "blind"
	CoverDeviceClassCurtain CoverDeviceClass = "curtain"
	CoverDeviceClassDamper  CoverDeviceClass = "damper"
	CoverDeviceClassDoor    CoverDeviceClass = "door"
	CoverDeviceClassGarage  CoverDeviceClass = "garage"
	CoverDeviceClassGate    CoverDeviceClass = "gate"
	CoverDeviceClassShade   CoverDeviceClass = "shade"
	CoverDeviceClassShutter CoverDeviceClass = "shutter"
	CoverDeviceClassWindow  CoverDeviceClass = "window"
)

// String returns the wire value.
func (v CoverDeviceClass) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v CoverDeviceClass) Valid() bool {
	_, ok := validCoverDeviceClass[v]
	return ok
}

var validCoverDeviceClass = map[CoverDeviceClass]struct{}{
	CoverDeviceClassAwning:  {},
	CoverDeviceClassBlind:   {},
	CoverDeviceClassCurtain: {},
	CoverDeviceClassDamper:  {},
	CoverDeviceClassDoor:    {},
	CoverDeviceClassGarage:  {},
	CoverDeviceClassGate:    {},
	CoverDeviceClassShade:   {},
	CoverDeviceClassShutter: {},
	CoverDeviceClassWindow:  {},
}

// SwitchDeviceClass is the device class vocabulary of the switch platform.
type SwitchDeviceClass string

const (
	SwitchDeviceClassOutlet SwitchDeviceClass = "outlet"
	SwitchDeviceClassSwitch SwitchDeviceClass = "switch"
)

// String returns the wire value.
func (v SwitchDeviceClass) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v SwitchDeviceClass) Valid() bool {
	_, ok := validSwitchDeviceClass[v]
	return ok
}

var validSwitchDeviceClass = map[SwitchDeviceClass]struct{}{
	SwitchDeviceClassOutlet: {},
	SwitchDeviceClassSwitch: {},
}

// ButtonDeviceClass is the device class vocabulary of the button platform.
type ButtonDeviceClass string

const (
	ButtonDeviceClassIdentify ButtonDeviceClass = "identify"
	ButtonDeviceClassRestart  ButtonDeviceClass = "restart"
	ButtonDeviceClassUpdate   ButtonDeviceClass = "update"
)

// String returns the wire value.
func (v ButtonDeviceClass) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v ButtonDeviceClass) Valid() bool {
	_, ok := validButtonDeviceClass[v]
	return ok
}

var validButtonDeviceClass = map[ButtonDeviceClass]struct{}{
	ButtonDeviceClassIdentify: {},
	ButtonDeviceClassRestart:  {},
	ButtonDeviceClassUpdate:   {},
}

// EventDeviceClass is the device class vocabulary of the event platform.
type EventDeviceClass string

const (
	EventDeviceClassButton   EventDeviceClass = "button"
	EventDeviceClassDoorbell EventDeviceClass = "doorbell"
	EventDeviceClassMotion   EventDeviceClass = "motion"
)

// String returns the wire value.
func (v EventDeviceClass) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v EventDeviceClass) Valid() bool {
	_, ok := validEventDeviceClass[v]
	return ok
}

var validEventDeviceClass = map[EventDeviceClass]struct{}{
	EventDeviceClassButton:   {},
	EventDeviceClassDoorbell: {},
	EventDeviceClassMotion:   {},
}

// UpdateDeviceClass is the device class vocabulary of the update platform.
type UpdateDeviceClass string

const (
	UpdateDeviceClassFirmware UpdateDeviceClass = "firmware"
)

// String returns the wire value.
func (v UpdateDeviceClass) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v UpdateDeviceClass) Valid() bool {
	_, ok := validUpdateDeviceClass[v]
	return ok
}

var validUpdateDeviceClass = map[UpdateDeviceClass]struct{}{
	UpdateDeviceClassFirmware: {},
}

// HumidifierDeviceClass is the device class vocabulary of the humidifier platform.
type HumidifierDeviceClass string

const (
	HumidifierDeviceClassDehumidifier HumidifierDeviceClass = "dehumidifier"
	HumidifierDeviceClassHumidifier   HumidifierDeviceClass = "humidifier"
)

// String returns the wire value.
func (v HumidifierDeviceClass) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v HumidifierDeviceClass) Valid() bool {
	_, ok := validHumidifierDeviceClass[v]
	return ok
}

var validHumidifierDeviceClass = map[HumidifierDeviceClass]struct{}{
	HumidifierDeviceClassDehumidifier: {},
	HumidifierDeviceClassHumidifier:   {},
}

// ValveDeviceClass is the device class vocabulary of the valve platform.
type ValveDeviceClass string

const (
	ValveDeviceClassGas   ValveDeviceClass = "gas"
	ValveDeviceClassWater ValveDeviceClass = "water"
)

// String returns the wire value.
func (v ValveDeviceClass) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v ValveDeviceClass) Valid() bool {
	_, ok := validValveDeviceClass[v]
	return ok
}

var validValveDeviceClass = map[ValveDeviceClass]struct{}{
	ValveDeviceClassGas:   {},
	ValveDeviceClassWater: {},
}

// MediaPlayerDeviceClass is the device class vocabulary of the media_player platform.
type MediaPlayerDeviceClass string

const (
	MediaPlayerDeviceClassProjector MediaPlayerDeviceClass = "projector"
	MediaPlayerDeviceClassReceiver  MediaPlayerDeviceClass = "receiver"
	MediaPlayerDeviceClassSpeaker   MediaPlayerDeviceClass = "speaker"
	MediaPlayerDeviceClassTV        MediaPlayerDeviceClass = "tv"
)

// String returns the wire value.
func (v MediaPlayerDeviceClass) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v MediaPlayerDeviceClass) Valid() bool {
	_, ok := validMediaPlayerDeviceClass[v]
	return ok
}

var validMediaPlayerDeviceClass = map[MediaPlayerDeviceClass]struct{}{
	MediaPlayerDeviceClassProjector: {},
	MediaPlayerDeviceClassReceiver:  {},
	MediaPlayerDeviceClassSpeaker:   {},
	MediaPlayerDeviceClassTV:        {},
}

// NumberMode selects how Home Assistant renders a number entity.
type NumberMode string

const (
	NumberModeAuto   NumberMode = "auto"
	NumberModeBox    NumberMode = "box"
	NumberModeSlider NumberMode = "slider"
)

// String returns the wire value.
func (v NumberMode) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v NumberMode) Valid() bool {
	_, ok := validNumberMode[v]
	return ok
}

var validNumberMode = map[NumberMode]struct{}{
	NumberModeAuto:   {},
	NumberModeBox:    {},
	NumberModeSlider: {},
}

// TextMode selects how Home Assistant renders a text entity.
type TextMode string

const (
	TextModePassword TextMode = "password"
	TextModeText     TextMode = "text"
)

// String returns the wire value.
func (v TextMode) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v TextMode) Valid() bool {
	_, ok := validTextMode[v]
	return ok
}

var validTextMode = map[TextMode]struct{}{
	TextModePassword: {},
	TextModeText:     {},
}

// SourceType is a device_tracker's positioning source. "router" is what makes a
// tracker usable for presence without any coordinates.
type SourceType string

const (
	SourceTypeBluetooth   SourceType = "bluetooth"
	SourceTypeBluetoothLe SourceType = "bluetooth_le"
	SourceTypeGPS         SourceType = "gps"
	SourceTypeRouter      SourceType = "router"
)

// String returns the wire value.
func (v SourceType) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v SourceType) Valid() bool {
	_, ok := validSourceType[v]
	return ok
}

var validSourceType = map[SourceType]struct{}{
	SourceTypeBluetooth:   {},
	SourceTypeBluetoothLe: {},
	SourceTypeGPS:         {},
	SourceTypeRouter:      {},
}

// HVACMode is a climate entity's operating mode.
type HVACMode string

const (
	HVACModeAuto     HVACMode = "auto"
	HVACModeCool     HVACMode = "cool"
	HVACModeDry      HVACMode = "dry"
	HVACModeFanOnly  HVACMode = "fan_only"
	HVACModeHeat     HVACMode = "heat"
	HVACModeHeatCool HVACMode = "heat_cool"
	HVACModeOff      HVACMode = "off"
)

// String returns the wire value.
func (v HVACMode) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v HVACMode) Valid() bool {
	_, ok := validHVACMode[v]
	return ok
}

var validHVACMode = map[HVACMode]struct{}{
	HVACModeAuto:     {},
	HVACModeCool:     {},
	HVACModeDry:      {},
	HVACModeFanOnly:  {},
	HVACModeHeat:     {},
	HVACModeHeatCool: {},
	HVACModeOff:      {},
}

// HVACAction is what a climate entity is currently doing, as opposed to what it
// is set to.
type HVACAction string

const (
	HVACActionCooling    HVACAction = "cooling"
	HVACActionDefrosting HVACAction = "defrosting"
	HVACActionDrying     HVACAction = "drying"
	HVACActionFan        HVACAction = "fan"
	HVACActionHeating    HVACAction = "heating"
	HVACActionIdle       HVACAction = "idle"
	HVACActionOff        HVACAction = "off"
	HVACActionPreheating HVACAction = "preheating"
)

// String returns the wire value.
func (v HVACAction) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v HVACAction) Valid() bool {
	_, ok := validHVACAction[v]
	return ok
}

var validHVACAction = map[HVACAction]struct{}{
	HVACActionCooling:    {},
	HVACActionDefrosting: {},
	HVACActionDrying:     {},
	HVACActionFan:        {},
	HVACActionHeating:    {},
	HVACActionIdle:       {},
	HVACActionOff:        {},
	HVACActionPreheating: {},
}

// ColorMode is a light's color capability. Unlike most mode lists, MQTT does
// constrain this one: supported_color_modes is schema-validated.
type ColorMode string

const (
	ColorModeBrightness ColorMode = "brightness"
	ColorModeColorTemp  ColorMode = "color_temp"
	ColorModeHs         ColorMode = "hs"
	ColorModeOnoff      ColorMode = "onoff"
	ColorModeRgb        ColorMode = "rgb"
	ColorModeRgbw       ColorMode = "rgbw"
	ColorModeRgbww      ColorMode = "rgbww"
	ColorModeUnknown    ColorMode = "unknown"
	ColorModeWhite      ColorMode = "white"
	ColorModeXy         ColorMode = "xy"
)

// String returns the wire value.
func (v ColorMode) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v ColorMode) Valid() bool {
	_, ok := validColorMode[v]
	return ok
}

var validColorMode = map[ColorMode]struct{}{
	ColorModeBrightness: {},
	ColorModeColorTemp:  {},
	ColorModeHs:         {},
	ColorModeOnoff:      {},
	ColorModeRgb:        {},
	ColorModeRgbw:       {},
	ColorModeRgbww:      {},
	ColorModeUnknown:    {},
	ColorModeWhite:      {},
	ColorModeXy:         {},
}

// CoverState is a cover's reported state.
type CoverState string

const (
	CoverStateClosed  CoverState = "closed"
	CoverStateClosing CoverState = "closing"
	CoverStateOpen    CoverState = "open"
	CoverStateOpening CoverState = "opening"
)

// String returns the wire value.
func (v CoverState) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v CoverState) Valid() bool {
	_, ok := validCoverState[v]
	return ok
}

var validCoverState = map[CoverState]struct{}{
	CoverStateClosed:  {},
	CoverStateClosing: {},
	CoverStateOpen:    {},
	CoverStateOpening: {},
}

// ValveState is a valve's reported state.
type ValveState string

const (
	ValveStateClosed  ValveState = "closed"
	ValveStateClosing ValveState = "closing"
	ValveStateOpen    ValveState = "open"
	ValveStateOpening ValveState = "opening"
)

// String returns the wire value.
func (v ValveState) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v ValveState) Valid() bool {
	_, ok := validValveState[v]
	return ok
}

var validValveState = map[ValveState]struct{}{
	ValveStateClosed:  {},
	ValveStateClosing: {},
	ValveStateOpen:    {},
	ValveStateOpening: {},
}

// LockState is a lock's reported state.
type LockState string

const (
	LockStateJammed    LockState = "jammed"
	LockStateLocked    LockState = "locked"
	LockStateLocking   LockState = "locking"
	LockStateOpen      LockState = "open"
	LockStateOpening   LockState = "opening"
	LockStateUnlocked  LockState = "unlocked"
	LockStateUnlocking LockState = "unlocking"
)

// String returns the wire value.
func (v LockState) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v LockState) Valid() bool {
	_, ok := validLockState[v]
	return ok
}

var validLockState = map[LockState]struct{}{
	LockStateJammed:    {},
	LockStateLocked:    {},
	LockStateLocking:   {},
	LockStateOpen:      {},
	LockStateOpening:   {},
	LockStateUnlocked:  {},
	LockStateUnlocking: {},
}

// AlarmState is an alarm control panel's reported state.
type AlarmState string

const (
	AlarmStateArmedAway         AlarmState = "armed_away"
	AlarmStateArmedCustomBypass AlarmState = "armed_custom_bypass"
	AlarmStateArmedHome         AlarmState = "armed_home"
	AlarmStateArmedNight        AlarmState = "armed_night"
	AlarmStateArmedVacation     AlarmState = "armed_vacation"
	AlarmStateArming            AlarmState = "arming"
	AlarmStateDisarmed          AlarmState = "disarmed"
	AlarmStateDisarming         AlarmState = "disarming"
	AlarmStatePending           AlarmState = "pending"
	AlarmStateTriggered         AlarmState = "triggered"
)

// String returns the wire value.
func (v AlarmState) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v AlarmState) Valid() bool {
	_, ok := validAlarmState[v]
	return ok
}

var validAlarmState = map[AlarmState]struct{}{
	AlarmStateArmedAway:         {},
	AlarmStateArmedCustomBypass: {},
	AlarmStateArmedHome:         {},
	AlarmStateArmedNight:        {},
	AlarmStateArmedVacation:     {},
	AlarmStateArming:            {},
	AlarmStateDisarmed:          {},
	AlarmStateDisarming:         {},
	AlarmStatePending:           {},
	AlarmStateTriggered:         {},
}

// VacuumActivity is a vacuum's reported activity.
type VacuumActivity string

const (
	VacuumActivityCleaning  VacuumActivity = "cleaning"
	VacuumActivityDocked    VacuumActivity = "docked"
	VacuumActivityError     VacuumActivity = "error"
	VacuumActivityIdle      VacuumActivity = "idle"
	VacuumActivityPaused    VacuumActivity = "paused"
	VacuumActivityReturning VacuumActivity = "returning"
)

// String returns the wire value.
func (v VacuumActivity) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v VacuumActivity) Valid() bool {
	_, ok := validVacuumActivity[v]
	return ok
}

var validVacuumActivity = map[VacuumActivity]struct{}{
	VacuumActivityCleaning:  {},
	VacuumActivityDocked:    {},
	VacuumActivityError:     {},
	VacuumActivityIdle:      {},
	VacuumActivityPaused:    {},
	VacuumActivityReturning: {},
}

// LawnMowerActivity is a lawn mower's reported activity.
type LawnMowerActivity string

const (
	LawnMowerActivityDocked    LawnMowerActivity = "docked"
	LawnMowerActivityError     LawnMowerActivity = "error"
	LawnMowerActivityMowing    LawnMowerActivity = "mowing"
	LawnMowerActivityPaused    LawnMowerActivity = "paused"
	LawnMowerActivityReturning LawnMowerActivity = "returning"
)

// String returns the wire value.
func (v LawnMowerActivity) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v LawnMowerActivity) Valid() bool {
	_, ok := validLawnMowerActivity[v]
	return ok
}

var validLawnMowerActivity = map[LawnMowerActivity]struct{}{
	LawnMowerActivityDocked:    {},
	LawnMowerActivityError:     {},
	LawnMowerActivityMowing:    {},
	LawnMowerActivityPaused:    {},
	LawnMowerActivityReturning: {},
}

// HumidifierAction is what a humidifier is currently doing.
type HumidifierAction string

const (
	HumidifierActionDrying      HumidifierAction = "drying"
	HumidifierActionHumidifying HumidifierAction = "humidifying"
	HumidifierActionIdle        HumidifierAction = "idle"
	HumidifierActionOff         HumidifierAction = "off"
)

// String returns the wire value.
func (v HumidifierAction) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v HumidifierAction) Valid() bool {
	_, ok := validHumidifierAction[v]
	return ok
}

var validHumidifierAction = map[HumidifierAction]struct{}{
	HumidifierActionDrying:      {},
	HumidifierActionHumidifying: {},
	HumidifierActionIdle:        {},
	HumidifierActionOff:         {},
}

// MediaPlayerState is a media player's reported state.
type MediaPlayerState string

const (
	MediaPlayerStateBuffering MediaPlayerState = "buffering"
	MediaPlayerStateIdle      MediaPlayerState = "idle"
	MediaPlayerStateOff       MediaPlayerState = "off"
	MediaPlayerStateOn        MediaPlayerState = "on"
	MediaPlayerStatePaused    MediaPlayerState = "paused"
	MediaPlayerStatePlaying   MediaPlayerState = "playing"
	MediaPlayerStateStandby   MediaPlayerState = "standby"
)

// String returns the wire value.
func (v MediaPlayerState) String() string { return string(v) }

// Valid reports whether v is one of the values Home Assistant declared at
// this catalog's snapshot. A false result is not proof of an illegal value on a
// newer Home Assistant — check SnapshotVersion before treating it as one.
func (v MediaPlayerState) Valid() bool {
	_, ok := validMediaPlayerState[v]
	return ok
}

var validMediaPlayerState = map[MediaPlayerState]struct{}{
	MediaPlayerStateBuffering: {},
	MediaPlayerStateIdle:      {},
	MediaPlayerStateOff:       {},
	MediaPlayerStateOn:        {},
	MediaPlayerStatePaused:    {},
	MediaPlayerStatePlaying:   {},
	MediaPlayerStateStandby:   {},
}
